### ISSUE TITLE
[🚨BUG] form-data 형식의 데이터를 React 프로젝트에서 전송했을 때 오류가 발생합니다.

### ISSUE THREAD

**Issue by otcroz** [polaris-book-page/front-end#27]
**버그 설명**
form-data 형식의 데이터가 전송되지 않습니다.
정확히는 text와 file이 포함된 form-data 형식의 데이터를 전송하는 방법을 찾지 못했습니다.

![image](https://github.com/polaris-book-page/front-end/assets/79989242/415ba624-22ff-49e5-8dc2-7b2585722d98)
Postman에서는 form-data 형식으로 데이터를 전송하여 response가 성공적으로 출력되었습니다. 그래서 react 단의 문제라고 생각했습니다.

**버그 재현**
버그가 재현되는 순서를 설명해주세요.
ex) A 화면에서 버튼을 클릭한 후 스크롤을 했을 때 오류가 발생합니다.
관련 오류의 스크린샷을 남겨주면 팀원들이 버그를 파악하기 수월할 것입니다.
1. 프로필 수정 페이지(EditProfilePage)로 이동
2. 프로필 이미지를 클릭하여 사진을 선택합니다.
![image](https://github.com/polaris-book-page/front-end/assets/79989242/3d293bf6-108c-47c0-8975-fa16d4d745c9)

3. 티켓 정보 수정하기 텍스트를 클릭합니다.
4. 마이페이지로 넘어가지만, 프로필은 수정되지 않은 상태입니다. 콘솔 창에서 에러를 확인할 수 있습니다.
 - 웹페이지에서 발생한 에러 내용
![image](https://github.com/polaris-book-page/front-end/assets/79989242/65ee4702-cbcf-48e1-aa36-a136d4bd6738)
 
 - 백엔드 단에서 발생한 에러 내용
 ```
    [0]     const profileImage = req.file.location;
    [0]                                   ^
    [0]
    [0] TypeError: Cannot read properties of undefined (reading 'location')
```
` req.file.location`을 인식하지 못하는 것 보아, node.js 단에서 react에서 전송한 데이터(form-data)를 받을 때 `req.file` 인자로 받지 않는다고 생각했습니다. 콘솔에 찍었을 때, `req.file`은 `undefined`가 뜹니다.

**참고자료**
[HTTP multipart/form-data 로 이미지 전송하고 서버에서 처리하기 feat. React, Express, Multer](https://eastash.me/http-multipartform-data-feat-react-express-multer#heading-3-express-multipartform-data)
[React | Formdata로 이미지, 텍스트 파일 전송하기](https://velog.io/@shackstack/React-Formdata%EB%A1%9C-%EC%9D%B4%EB%AF%B8%EC%A7%80-%ED%85%8D%EC%8A%A4%ED%8A%B8-%ED%8C%8C%EC%9D%BC-%EC%A0%84%EC%86%A1%ED%95%98%EA%B8%B0)
[[React] Form Data 전송](https://velog.io/@shin6403/React-Form-Data-%EC%A0%84%EC%86%A1)

상기 내용 이외에도 참고한 자료가 수두룩하지만 제가 유심히 확인하고 시도해 본 자료를 첨부합니다.

**Comment by otcroz** [comment]
**1번째 시도**

해당 페이지에서 '티켓 정보 수정하기' 텍스트를 클릭하면 아래 함수가 실행됩니다.
```js
      let formData = new FormData();
      
      formData.append("profileImage", image)
      formData.append("dir", 'profile')
      formData.append("nickname", userNickname)

      **mutate**(formData)
```
FormData 객체를 생성한 뒤, 키, 속성으로 매칭하여 데이터를 넣었습니다. 이때 키는 postman에서 사용한 키와 동일한 이름을 사용했습니다.
![image](https://github.com/polaris-book-page/front-end/assets/79989242/9bb115cf-5d94-43cd-9ccd-2bac8764de2d)

```js
    const { mutate } = useMutation({
        mutationFn: async (profile) => {
            const res = await axios.put(`http://localhost:3001/mypage/modify`, profile, {
                headers: {
                    "Content-Type": `multipart/form-data`,
                },
                withCredentials: true
            })
            const data = res.data;

            console.log(data);

            return data;
        },
        onSuccess: (data) => {
            console.log("update profile success.")
        },
        onError: (data) => {
            console.log("update profile failure.")
        }
        
    })
```

mutate 함수가 실행되면 useMutation의 mutationFn이 실행됩니다. axios를 호출하는 부분에서 오류가 발생합니다. headers를 `Content-Type: multipart/form-data`로 작성했는데 위에 작성했던 오류가 발생합니다.

**Comment by otcroz** [comment]
**2번째 시도**
Blob 객체를 사용해보는 방법을 생각했습니다. 이 객체를 사용하게 되면 text 타입의 name, dir은 json 형태로 묶은 뒤에 전송해줘야 합니다.

```js
    const handleUpdate = () => {
        let formData = new FormData();

        const data = {
            "nickname": userNickname,
            "dir": "profile",
        }
        
        formData.append("profileImage", image)
        formData.append("data", new Blob([JSON.stringify(data), {type: "application/json"}]))

        mutate(formData)
    }
```

이렇게 전송하면 데이터 형태는 아래와 같습니다.
```
**form data**
profileImage: (file)
data: {"dir": "profile", "nickname": userNickname}
```

mutate 함수는 변경사항이 없어 코드를 생략하겠습니다. 하지만 이렇게 전송해도 오류가 발생합니다. 오류 발생 원인은 다음과 같습니다.

`MulterError: Unexpected field`
multer에서 오류가 발생합니다. 아마도, node.js 프로젝트의 **mypage.js** 29번째 줄 `upload.single("profileImage")`에서 발생하는 오류인 것 같습니다. **aws.storage.js** 파일의 22번째 줄을 확인하면, `req.body.dir`에서 값이 없기에 발생하는 오류라고 예상했습니다.
그러나 `req.body.dir`는 이미지 업로드와 관련된 타 라우터에서도 사용되기 때문에 수정할 수 없습니다. 다른 방안을 찾아봐야 할 것 같습니다..

**Comment by otcroz** [comment]
브랜치(formdata-error) 올려두었습니다.. 에러 상황을 확인하고 싶으면 브랜치 받아오면 될 것 같아요.

**Comment by kjh073** [comment]
여러 방법으로 시도해봤는데 postman에서 전송할 때와 프론트 단에서 전송할 때 받는 이미지 형식이 다른 것 같습니다.
- postman
<img width="513" alt="Screen Shot 2024-01-31 at 1 57 24" src="https://github.com/polaris-book-page/front-end/assets/82260747/b5e60176-f7e0-4743-8eb4-29631a4ee071">

- 프론트
<img width="355" alt="Screen Shot 2024-01-31 at 0 57 07" src="https://github.com/polaris-book-page/front-end/assets/82260747/2dad277f-4e0c-4923-b791-e47c6247cc34">

이 차이가 있어 업로드가 되지 않는 것일까요?

**Comment by kjh073** [comment]
방법을 찾은 것 같습니다!
```
formData.append("profileImage", file)
```
이 코드를 적용하면 이미지가 바뀝니다! input tag에서 type을 file로 받아서 그런 것 같아요. 
하지만 s3에 업로드 된 파일을 확인해보니 /undefined 디렉토리에 저장되는데 그것만 해결하면 될 것 같습니다.

**Comment by otcroz** [comment]
오오.. 적용해보겠습니다. 감사합니다!

**Comment by otcroz** [comment]
위의 코드를 적용하여 이미지 문제를 해결했습니다. /undefined에 저장되는 오류는 아래 방법을 통해 해결했습니다.
```js
        formData.append('dir', 'profile')
        formData.append('profileImage', file)
        formData.append('nickname', userNickname)
```

fromData에 데이터를 넣을 때 S3 디렉토리 관련 정보를 먼저 삽입하면 S3에서 /profile 디렉토리에 사진이 잘 저장됩니다.
덕분에 해결했어요. 감사합니다!
