### ISSUE TITLE
[🚨BUG] 북킷리스트 페이지에 들어갔을 때 오류가 발생합니다.

### ISSUE THREAD

**Issue by otcroz** [polaris-book-page/front-end#37]
**버그 설명**
북킷리스트 페이지에 들어가면 오류가 발생합니다.
![image](https://github.com/polaris-book-page/front-end/assets/79989242/d6bc8e21-98a2-4833-b522-73df3fe4707d)

**버그 재현**
버그가 재현되는 순서를 설명해주세요.
ex) A 화면에서 버튼을 클릭한 후 스크롤을 했을 때 오류가 발생합니다.
관련 오류의 스크린샷을 남겨주면 팀원들이 버그를 파악하기 수월할 것입니다.
1. 북킷리스트(http://localhost:3000/mypage/list) 페이지에 들어갑니다.
2. 오류가 발생합니다.
GridBox에서 발생하는 오류입니다. 코드를 확인해봤더니 GridBox의 17번째 줄에 `item.author.indexOf('(') !== -1`에서 오류가 발생합니다. 
![image](https://github.com/polaris-book-page/front-end/assets/79989242/7e1db62f-b8e8-497c-811e-124c0df11093)
item을 출력했습니다. author이 없어서 발생한 오류 같아요.

**Comment by otcroz** [comment]
오류를 해결했습니다. 당시 like 스키마에 있던 데이터의 형식과 현 데이터의 형식이 다릅니다.
당시에는 author 속성이 없었습니다. 하지만 현재는 좋아요를 눌렀을 때 데이터의 형식이 아래와 같습니다.
```
    {
        "_id": "65e339ff4abb0774f8dd2886",
        "isbn": 9788994621937,
        "userId": "ccc",
        "title": "말하면 힘이 세지는 말",
        "author": "미야니시 타츠야",
        "publisher": "책속물고기",
        "cover": "https://image.aladin.co.kr/product/6193/82/cover/8994621938_1.jpg",
        "nickname": "닉네임1"
    },
```

**Comment by kjh073** [comment]
제가 확인해보았을 때, 여러가지 문제점이 있었습니다.
1. 거의 대부분의 책들은 isbn13이 있지만 isbn만 있는 책들도 있었습니다.
2. 베스트셀러로 불러와지는 책들은 책 정보에 저장이 안 되어 book db에 저장되지 않아 책 정보를 불러오지 못합니다.

때문에 
1번 문제는 isbn은 문제+숫자로 되어있기에 number로 되어있는 isbn을 string의 형식으로 바꿔야할 것 같습니다. 
2번은 베스트셀러를 불러올 때도 book db에 저장해야할 것 같습니다.
