### ISSUE TITLE
[🚨BUG] 캘린더 일자 설정 후 재설정 시 이후 날짜가 보이지 않습니다.

### ISSUE THREAD

**Issue by kjh073** [polaris-book-page/front-end#52]
**버그 설명**
리뷰 생성 중 캘린더로 날짜를 재지정할 때 선택한 날짜 이후의 달력이 뜨지 않습니다.
가령 유저가 날짜를 잘못 입력해 재설정하고 싶은 경우, 불편함을 겪을 것으로 예상됩니다.

https://github.com/polaris-book-page/front-end/assets/82260747/ce002a44-ed53-48a3-a4c8-8585d742e8b6

**버그 재현**
1. 리뷰 생성 페이지로 이동
2. 캘린더에서 날짜 지정 시 현재보다 이전 달의 날짜로 지정
3. 설정한 날짜 다시 선택(읽기 시작한 날짜를 5월 1일로 지정했다면 다시 읽기 시작한 날짜 클릭)
4. 선택한 달 이후의 달력은 보이지 않는 것을 확인할 수 있음

**참고자료**
https://stackoverflow.com/questions/49850917/how-do-i-disable-future-dates-in-reactjs
이 글에서는 max를 활용하라고 합니다. 
하지만 maxDate가 new date() 임에도 왜 이런 현상이 일어나는지 모르겠습니다만 더 찾아봐야할 것 같습니다.

**Comment by otcroz** [comment]
제 생각에는 maxDate가 new date()로 초기화되어 있어서 다음 날짜를 선택하지 못하는 것 같아요. new date()가 현재 날짜 Date 객체를 불러오는 코드라서.. maxDate에 대한 설정을 없애면 해결될 것 같습니다.

**Comment by otcroz** [comment]
알고보니까 다른 오류였습니다. 오른쪽 화살표를 보이게 하는 오류였는데, 잘못된 조건 설정이었더라고요. 그래서 화살표에 대한 조건을 제거했습니다.
```js
{currentDate.getMonth() == date.getMonth() && date.getFullYear() == currentDate.getFullYear() ? "" : <ArrowRight color='#CBCDFA' width={10}/>}
``가
조건은 사용자가 선택한 달이 같으면서 연도가 같은 경우 화살표를 보이지 않게 하는 겁니다. 애초에 조건을 걸어야 할 주체가 잘못된 것이죠. (사용자가 선택한 날짜에 대해 조건을 달았던 것.)
