### ISSUE TITLE
[🚨BUG] 우주 페이지 렌더링 오류

### ISSUE THREAD

**Issue by otcroz** [polaris-book-page/front-end#70]
**버그 설명**
![image](https://github.com/user-attachments/assets/e3aaafd4-b6bc-4821-b69f-89559410feb7)
로그인 후에 universe 페이지로 이동하면 위 사진과 같은 오류가 발생합니다.
처음에는 사용자가 작성한 리뷰 목록이 불러와지지 않습니다.
새로고침을 하면 잘 실행됩니다.

**버그 재현**
1. http://localhost:3000/mypage/universe 페이지 접속
2. 사용자 로그인 화면으로 이동
3. 로그인 후 universe page 이동
4. 에러를 확인할 수 있습니다.

**참고자료**

**Comment by kjh073** [comment]
우주 페이지에  리뷰를 불러오기 위해 사용되는 백엔드 API에 콘솔을 찍어보았습니다.
- 백엔드 일부 코드
`router.get('/star-review', async (req, res) => {
    try {
        console.log("userId", req.session.userId )
        const results = await Review.find({ userId: req.session.userId })
        console.log("result", results[0])
        if (results.length === 0) {
            console.log("in?????????????/ back")
            return res.status(200).json({ 
                findMyReview: false, 
                message: 'No review corresponding to this user' 
            });
        }
        //...
        `
 - 실행 후 찍힌 백엔드 콘솔
<img width="241" alt="Screen Shot 2024-07-27 at 1 55 30" src="https://github.com/user-attachments/assets/9a0b98ef-c886-47e4-baff-2cce2b7b7563">

프론트 측에서는 Auth.js에서 state로 로그인한 사용자의 userId를 전달해주기 때문에 페이지가 렌더링 되기 전, 유저의 세션이 잘 전달되는 줄 알았습니다. 하지만 백엔드 측에서 콘솔을 출력해본 결과 로그인 로직 실행 후 유저의 세션이 아직 저장되지 않은 채로 페이지가 렌더링된 것으로 보입니다.

유저의 세션이 저장되지 않은 상태에서 백엔드 API를 호출하는 경우를 방지하기 위해 queryClient로 유저의 세션이 생성되었는지 확인하는 조건문을 넣어 오류를 방지하였습니다.

**Comment by kjh073** [comment]
이 문제를 해결한 줄 알았지만 다른 오류가 발생했습니다.
다른 페이지에서 우주 페이지로 이동할 때는 행성들이 잘 뜨지만 우주 페이지에서 새로고침하면 아무 행성도 뜨지 않는 오류가 발생합니다.

**Comment by kjh073** [comment]
로그인하지 않은 상태에서 우주 페이지를 들어가면 로그인 페이지로 이동하는 주요 로직은 아래와 같습니다. 
```
//Auth.js
//...
if (checkUser.userId === 'none') {
	navigate("/auth/login", { state: pathname });
}
//...

//LoginPage.js
//...
if (state) {
    navigate(state, {state : UserAuthInfoCheck.userId });
} else {
    navigate("/");
}
//...

```

Auth.js에서 접속하려고 했던 페이지의 path를 state로 넘겨주고 로그인 후 navigate를 통해 해당 페이지로 이동하게 됩니다.
로그인 페이지로 이동하기 전, 먼저 유저의 review list는 false로 불러와집니다.
<img width="302" alt="Screen Shot 2024-07-30 at 17 34 17" src="https://github.com/user-attachments/assets/fa2f7c1d-594c-48b8-9ddc-6ad95eca26a0">

로그인 후 원 페이지로 돌아갈 때 페이지가 refresh되지 않기 때문에 리뷰에 관한 쿼리도 재실행되지 않는 것으로 보입니다. 때문에 리뷰 리스트가 없는 상태에서 우주 페이지로 바로 이동하게 되니 undefined 오류가 발생하였던 것 같습니다.

때문에 로그인된 유저 아이디가 없으면 백엔드 측에서 res.status(500)을 보내도록 수정하였습니다.
